"""
SEED COURSES — run once to populate the course catalogue.
Inserts 6 course skeletons into MongoDB.
Actual lesson content is generated by Gemini on first request (lazy).

Usage: python seed_courses.py
"""
import asyncio
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from motor.motor_asyncio import AsyncIOMotorClient
from config import MONGODB_URI
from datetime import datetime

COURSES = [
  {
    "title":       "Onion Farming A-Z",
    "titleMr":     "कांदा शेती संपूर्ण मार्गदर्शन",
    "titleHi":     "प्याज की खेती A से Z",
    "description": "Complete guide to onion farming — soil prep to market selling.",
    "category":    "CROP_MANAGEMENT",
    "targetCrops": ["onion"],
    "difficulty":  "BEGINNER",
    "targetAudience": "BEGINNER",
    "estimatedHours": 4,
    "isPublished": True,
    "createdBy":   "ADMIN",
    "enrollmentCount": 0,
    "modules": [
      {
        "title": "Soil Preparation", "titleMr": "माती तयारी", "sequence": 1,
        "lessons": [
          {
            "title": "Understanding Soil for Onion Farming",
            "titleMr": "कांद्यासाठी माती समजून घ्या",
            "sequence": 1, "type": "THEORY",
            "aiPrompt": "Teach about ideal soil for onion farming in Maharashtra. Cover: soil type (sandy loam), pH range (6.0-7.0), organic matter importance, how to test soil at home, how to correct pH with lime or sulfur. Use Nashik/Pune region examples.",
            "assignment": {
              "task":   "Collect soil from 3 spots in your field. Feel the texture — is it sandy, clay, or loam?",
              "taskMr": "तुमच्या शेतातून ३ ठिकाणांची माती घ्या. पोत तपासा — वाळूसारखी, चिकट की मध्यम?",
            },
            "estimatedMinutes": 15, "isPublished": True,
          },
          {
            "title": "Composting and Organic Matter",
            "titleMr": "कंपोस्ट आणि सेंद्रिय पदार्थ",
            "sequence": 2, "type": "PRACTICAL",
            "aiPrompt": "Teach how to make and use compost for onion farming. Cover: why organic matter matters for onion quality, how to make a simple compost pit, when and how much to apply, FYM (Farm Yard Manure) dosage per acre.",
            "estimatedMinutes": 20, "isPublished": True,
          },
        ]
      },
      {
        "title": "Variety Selection & Sowing", "titleMr": "वाण निवड आणि पेरणी", "sequence": 2,
        "lessons": [
          {
            "title": "Choosing the Right Onion Variety",
            "titleMr": "योग्य कांद्याचे वाण निवडा",
            "sequence": 1, "type": "THEORY",
            "aiPrompt": "Teach about onion varieties for Maharashtra. Cover: Bhima Kiran, Bhima Raj, Agrifound Light Red (for kharif), Bhima Super (for rabi), NHRDF varieties. Which variety for which season and market. Storage life of each variety.",
            "estimatedMinutes": 15, "isPublished": True,
          },
          {
            "title": "Nursery Preparation and Transplanting",
            "titleMr": "रोपवाटिका आणि पुनर्लागवड",
            "sequence": 2, "type": "PRACTICAL",
            "aiPrompt": "Teach nursery preparation for onion seedlings and transplanting. Cover: nursery bed preparation, seed treatment with Thiram, watering schedule, when seedlings are ready (5-6 weeks, 15cm tall), spacing for transplanting (15x10cm), how to transplant without damaging roots.",
            "estimatedMinutes": 25, "isPublished": True,
          },
        ]
      },
      {
        "title": "Irrigation & Fertilizers", "titleMr": "पाणी व्यवस्थापन आणि खते", "sequence": 3,
        "lessons": [
          {
            "title": "Irrigation Schedule for Onion",
            "sequence": 1, "type": "THEORY",
            "aiPrompt": "Teach irrigation management for onion crop. Cover: critical water stages (establishment, bulb initiation, bulbing), drip vs furrow irrigation, water requirement per week, how to identify over/under watering, stopping irrigation 2 weeks before harvest for storage quality.",
            "estimatedMinutes": 15, "isPublished": True,
          },
          {
            "title": "Fertilizer Schedule — NPK for Onion",
            "sequence": 2, "type": "THEORY",
            "aiPrompt": "Teach complete fertilizer management for onion. Cover: basal dose (40kg Urea + 250kg SSP + 50kg MOP per acre), top dressing schedule at 30 and 60 days, micronutrients (Boron for bulb size), foliar sprays, fertigatoin through drip, signs of nutrient deficiency.",
            "estimatedMinutes": 20, "isPublished": True,
          },
        ]
      },
    ]
  },

  {
    "title":       "Organic Farming for Beginners",
    "titleMr":     "सेंद्रिय शेती - नवख्यांसाठी",
    "titleHi":     "जैविक खेती शुरुआती गाइड",
    "description": "Start your organic farming journey — no chemicals, better prices.",
    "category":    "ORGANIC_FARMING",
    "targetCrops": [],
    "difficulty":  "BEGINNER",
    "targetAudience": "ALL",
    "estimatedHours": 5,
    "isPublished": True,
    "createdBy":   "ADMIN",
    "enrollmentCount": 0,
    "modules": [
      {
        "title": "Why Organic?", "sequence": 1,
        "lessons": [
          {
            "title": "Understanding Organic Farming",
            "sequence": 1, "type": "THEORY",
            "aiPrompt": "Teach why organic farming is becoming important in Maharashtra. Cover: soil health degradation from chemical overuse, premium prices for organic produce (20-50% more), organic certification process in India (PGS-India for small farmers), which crops get best organic premium (vegetables, pulses, spices).",
            "estimatedMinutes": 20, "isPublished": True,
          },
          {
            "title": "Making Jeevamrut — Liquid Biofertilizer",
            "sequence": 2, "type": "PRACTICAL",
            "aiPrompt": "Teach how to make Jeevamrut at home. Cover: ingredients (cow dung 10kg, cow urine 10L, jaggery 2kg, gram flour 2kg, water 200L), preparation method, fermentation for 48 hours, how to apply (drip/soil drench), shelf life, cost comparison vs chemical fertilizers.",
            "assignment": {
              "task":   "Try making a small 20L batch of Jeevamrut this week with these ingredients.",
              "taskMr": "या आठवड्यात छोटी २०L जीवामृत बनवण्याचा प्रयत्न करा.",
            },
            "estimatedMinutes": 25, "isPublished": True,
          },
        ]
      },
    ]
  },

  {
    "title":       "Drip Irrigation — Setup & Management",
    "titleMr":     "ठिबक सिंचन - बसवणे आणि व्यवस्थापन",
    "titleHi":     "ड्रिप सिंचाई — स्थापना और प्रबंधन",
    "description": "Save 50% water and increase yield with drip irrigation.",
    "category":    "IRRIGATION",
    "targetCrops": [],
    "difficulty":  "INTERMEDIATE",
    "targetAudience": "ALL",
    "estimatedHours": 3,
    "isPublished": True,
    "createdBy":   "ADMIN",
    "enrollmentCount": 0,
    "modules": [
      {
        "title": "Drip System Basics", "sequence": 1,
        "lessons": [
          {
            "title": "How Drip Irrigation Works",
            "sequence": 1, "type": "THEORY",
            "aiPrompt": "Teach how drip irrigation systems work for Indian farmers. Cover: components (mainline, submain, lateral pipes, drippers, filters, fertilizer tank), how water and nutrients reach roots, types of drippers (inline, online), pressure requirements, government subsidy (55-80% in Maharashtra — NHM scheme), cost per acre.",
            "estimatedMinutes": 20, "isPublished": True,
          },
        ]
      },
    ]
  },

  {
    "title":       "Government Schemes for Farmers",
    "titleMr":     "शेतकऱ्यांसाठी सरकारी योजना",
    "titleHi":     "किसानों के लिए सरकारी योजनाएं",
    "description": "Know your rights — all major central and state schemes explained simply.",
    "category":    "GOVT_SCHEMES",
    "targetCrops": [],
    "difficulty":  "EASY",
    "targetAudience": "ALL",
    "estimatedHours": 2,
    "isPublished": True,
    "createdBy":   "ADMIN",
    "enrollmentCount": 0,
    "modules": [
      {
        "title": "Central Government Schemes", "sequence": 1,
        "lessons": [
          {
            "title": "PM-KISAN — ₹6,000 Every Year",
            "sequence": 1, "type": "THEORY",
            "aiPrompt": "Teach PM-KISAN scheme in detail. Cover: what is it (₹6000/year in 3 installments), eligibility (all landholding farmers), how to apply (CSC center or pmkisan.gov.in), documents needed (Aadhaar, bank account, land records), how to check status online, what to do if installment is stuck, helpline 155261.",
            "estimatedMinutes": 15, "isPublished": True,
          },
          {
            "title": "PM Fasal Bima — Crop Insurance",
            "sequence": 2, "type": "THEORY",
            "aiPrompt": "Teach PMFBY crop insurance scheme. Cover: what it covers (natural disasters, pests, disease), premium rates (2% kharif, 1.5% rabi), how to apply (bank or CSC before deadline), deadline dates (31 July kharif, 31 Dec rabi), what to do when crop is damaged (72 hours reporting rule, helpline 14447), how to claim.",
            "estimatedMinutes": 20, "isPublished": True,
          },
        ]
      },
    ]
  },

  {
    "title":       "Soil Health & Fertilizer Management",
    "titleMr":     "मातीचे आरोग्य आणि खत व्यवस्थापन",
    "titleHi":     "मिट्टी स्वास्थ्य और उर्वरक प्रबंधन",
    "description": "Understand your soil and fertilize smarter, not more.",
    "category":    "SOIL_HEALTH",
    "targetCrops": [],
    "difficulty":  "INTERMEDIATE",
    "targetAudience": "ALL",
    "estimatedHours": 3,
    "isPublished": True,
    "createdBy":   "ADMIN",
    "enrollmentCount": 0,
    "modules": [
      {
        "title": "Soil Testing", "sequence": 1,
        "lessons": [
          {
            "title": "How to Get Your Soil Tested",
            "sequence": 1, "type": "PRACTICAL",
            "aiPrompt": "Teach soil testing for Maharashtra farmers. Cover: why soil testing is essential (save money on unnecessary fertilizers), where to get tested (krishi vigyan kendra, soil testing lab, private labs), Soil Health Card scheme (free government testing), how to collect soil sample correctly (from 10 spots mixed), how to read the report (NPK, pH, EC, organic carbon), what to do with results.",
            "estimatedMinutes": 20, "isPublished": True,
          },
        ]
      },
    ]
  },

  {
    "title":       "Cattle Health Management",
    "titleMr":     "जनावरांचे आरोग्य व्यवस्थापन",
    "titleHi":     "पशु स्वास्थ्य प्रबंधन",
    "description": "Keep your cattle healthy, productive and disease-free.",
    "category":    "CATTLE",
    "targetCrops": [],
    "difficulty":  "BEGINNER",
    "targetAudience": "ALL",
    "estimatedHours": 4,
    "isPublished": True,
    "createdBy":   "ADMIN",
    "enrollmentCount": 0,
    "modules": [
      {
        "title": "Daily Health Monitoring", "sequence": 1,
        "lessons": [
          {
            "title": "How to Monitor Your Cattle Daily",
            "sequence": 1, "type": "PRACTICAL",
            "aiPrompt": "Teach farmers how to do a daily cattle health check in 5 minutes. Cover: checking temperature (normal 38-39.5°C), eye and nose check (discharge = warning sign), appetite and rumination check, milk yield monitoring, hoof and skin inspection, what changes mean and when to call a vet. Make it practical for a farmer with 2-5 animals.",
            "estimatedMinutes": 20, "isPublished": True,
          },
          {
            "title": "Vaccination Schedule for Cattle",
            "sequence": 2, "type": "THEORY",
            "aiPrompt": "Teach the essential vaccination schedule for cattle in Maharashtra. Cover: FMD vaccine (every 6 months), HS vaccine (annual), BQ vaccine (annual), Brucellosis (female calves once), Theileria, government free vaccination camps, how to maintain a vaccination record, signs of vaccine reaction and what to do.",
            "estimatedMinutes": 15, "isPublished": True,
          },
        ]
      },
    ]
  },
]


async def seed():
    print("=" * 60)
    print("  Seeding KrishiMitra Course Catalogue")
    print("=" * 60)

    if not MONGODB_URI:
        print("ERROR: MONGODB_URI not set in .env")
        return

    client = AsyncIOMotorClient(MONGODB_URI)
    db     = client.get_default_database()
    col    = db["courses"]

    inserted = 0
    skipped  = 0

    for course in COURSES:
        existing = await col.find_one({"title": course["title"]})
        if existing:
            print(f"  ⏭️  Skipped (exists): {course['title']}")
            skipped += 1
            continue

        course["createdAt"] = datetime.utcnow()
        course["updatedAt"] = datetime.utcnow()
        await col.insert_one(course)
        print(f"  ✅ Inserted: {course['title']} ({len(course['modules'])} modules)")
        inserted += 1

    client.close()
    print(f"\n{'='*60}")
    print(f"  Done! {inserted} inserted, {skipped} skipped.")
    print(f"  Lesson content will be generated by Gemini on first request.")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(seed())